feat: Add new page flow trigger
weni-ai/insights-webapp pull request #24
Opened 2024-03-22 12:59 UTC by marihemori

## Description
### Type of Change

* * [ ] Bugfix
* * [x] Feature
* * [ ] Code style update (formatting, local variables)
* * [ ] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other

### Motivation and Context
New dash page needs to be added.

### Summary of Changes

### Design Files 
- Added a new chart component
- Added a data mock to the chart
- Added a new route to the new page

- [Design File 1](https://www.figma.com/file/P9yyN4D0wGMlzYMjOtHvv3/Insights?type=design&node-id=2-3&mode=design&t=lbamPI6bJORzQSJk-0)

### Demonstration 
![image](https://github.com/weni-ai/insights-webapp/assets/30897764/f5f882cb-cdfc-484a-b988-5382ba90b67a)

2024-03-22 17:29 UTC, Aldemylla requested changes

2024-03-22 17:29 UTC, Aldemylla commented on src/views/dashboards/Dashboard/FlowTrigger.vue
Replace spans and divs at this file to improve the readability

2024-03-25 20:56 UTC, marihemori commented on src/views/dashboards/Dashboard/FlowTrigger.vue
I added an improvement, check if it makes sense :)

2024-03-25 21:35 UTC, Aldemylla approved these changes

2024-03-26 12:46 UTC, merged